version: '3.8'

services:

  db:
    image: postgres:alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - backend/.env
    volumes:
      - .pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    tty: true
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py loaddata tmp/allbase.json &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: